sequenceDiagram
    participant Browser
    participant Server

    Browser->>Server: POST /new_note
    activate Server
    note right of Server: adding note to data.json
    Server-->>Browser: HTTP 302 Found (redirect: /notes)
    deactivate Server

    Browser->>Server: GET /notes
    activate Server
    Server-->>Browser: HTML page referencing main.js, main.css, and data.json
    deactivate Server

    Browser->>Server: GET /main.js
    activate Server
    Server-->>Browser: main.js
    deactivate Server

    Browser->>Server: GET /main.css
    activate Server
    Server-->>Browser: main.css
    deactivate Server

    Browser->>Server: GET /data.json
    activate Server
    Server-->>Browser: data.json
    deactivate Server
